from __future__ import annotations

from typing import Any, Dict, List


CONTROL_SEVERITY_WEIGHTS = {
    "CRITICAL": 10,
    "HIGH": 7,
    "MEDIUM": 4,
    "LOW": 2,
    "INFO": 1,
}


def build_control(control_id: str, framework: str, title: str, description: str, category: str, severity: str,
                  parameter: str, expected_value: Any, evaluation_type: str, remediation: str,
                  references: str, nist_mapping: str | None = None) -> Dict[str, Any]:
    return {
        "control_id": control_id,
        "framework": framework,
        "title": title,
        "description": description,
        "category": category,
        "severity": severity,
        "parameter": parameter,
        "expected_value": expected_value,
        "evaluation_type": evaluation_type,
        "remediation": remediation,
        "references": references,
        "nist_mapping": nist_mapping,
    }


def get_all_controls() -> List[Dict[str, Any]]:
    return [
        build_control(
            "CIS-NET-001",
            "CIS",
            "SSH Version 2 Enabled",
            "SSH version 2 should be used for secure administrative access.",
            "Secure Management",
            "HIGH",
            "ssh_version",
            2,
            "equals",
            "Recommended remediation — review before applying.\nCisco: ip ssh version 2\nFortinet: config system global\n set admin-ssh-version 2\nPalo Alto: set deviceconfig system ssh version 2",
            "CIS Benchmark - Secure Management",
            "NIST-NET-CM-001",
        ),
        build_control(
            "CIS-NET-002",
            "CIS",
            "Telnet Disabled",
            "Telnet should not be enabled for remote administrative access.",
            "Secure Management",
            "CRITICAL",
            "telnet_enabled",
            False,
            "equals",
            "Recommended remediation — review before applying.\nCisco: line vty 0 4\n transport input ssh\nFortinet: set admin-ssh-version 2\nPalo Alto: set deviceconfig system service disable-telnet yes",
            "CIS Benchmark - Secure Management",
            "NIST-NET-AC-001",
        ),
        build_control(
            "CIS-NET-003",
            "CIS",
            "Insecure HTTP Management Disabled",
            "HTTP administrative access should be disabled.",
            "Secure Management",
            "HIGH",
            "http_enabled",
            False,
            "equals",
            "Recommended remediation — review before applying.\nCisco: no ip http server\nFortinet: config system global\n set allowaccess https ssh\nPalo Alto: set deviceconfig system service disable-http yes",
            "CIS Benchmark - Secure Management",
            "NIST-NET-CM-001",
        ),
        build_control(
            "CIS-NET-004",
            "CIS",
            "HTTPS Management Enabled",
            "HTTPS should be enabled for secure management access when supported.",
            "Secure Management",
            "MEDIUM",
            "https_enabled",
            True,
            "equals",
            "Recommended remediation — review before applying.\nCisco: ip http secure-server\nFortinet: set allowaccess https\nPalo Alto: set deviceconfig system service disable-https no",
            "CIS Benchmark - Secure Management",
            "NIST-NET-AC-001",
        ),
        build_control(
            "CIS-NET-005",
            "CIS",
            "Administrative Logging Enabled",
            "Administrative actions should be logged for accountability.",
            "Audit and Accountability",
            "HIGH",
            "logging_enabled",
            True,
            "equals",
            "Recommended remediation — review before applying.\nCisco: logging buffered 4096\nFortinet: config log setting\n set status enable\nPalo Alto: set deviceconfig system syslog-server <SERVER>",
            "CIS Benchmark - Audit and Accountability",
            "NIST-NET-AU-001",
        ),
        build_control(
            "CIS-NET-006",
            "CIS",
            "Network Time Protocol Configured",
            "NTP should be configured for time synchronization.",
            "Configuration Management",
            "MEDIUM",
            "ntp_configured",
            True,
            "equals",
            "Recommended remediation — review before applying.\nCisco: ntp server <NTP_SERVER>\nFortinet: config system ntp\n set ntpsync enable\nPalo Alto: set deviceconfig system ntp server <SERVER>",
            "CIS Benchmark - Configuration Management",
            "NIST-NET-CM-001",
        ),
        build_control(
            "CIS-NET-007",
            "CIS",
            "Administrative Login Timeout Configured",
            "Administrative sessions should have a reasonable timeout.",
            "Secure Management",
            "MEDIUM",
            "login_timeout",
            1,
            "gt_zero",
            "Recommended remediation — review before applying.\nCisco: line vty 0 4\n exec-timeout 5 0\nFortinet: set admin-timeout 300\nPalo Alto: set deviceconfig system timeout 300",
            "CIS Benchmark - Secure Management",
            "NIST-NET-AC-001",
        ),
        build_control(
            "CIS-NET-008",
            "CIS",
            "Secure SNMP Configuration",
            "SNMP should only be considered secure when configured securely.",
            "Secure Management",
            "HIGH",
            "snmp_secure",
            True,
            "equals",
            "Recommended remediation — review before applying.\nCisco: no snmp-server community public RO\nFortinet: config system snmp community\n delete 1\nPalo Alto: set snmp-server community <COMMUNITY> authorization read-only",
            "CIS Benchmark - Secure Management",
            "NIST-NET-CM-001",
        ),
        build_control(
            "CIS-NET-009",
            "CIS",
            "Strong Password Policy",
            "Administrative credentials should follow a strong password policy.",
            "Identity Management",
            "CRITICAL",
            "password_policy",
            "strong",
            "equals",
            "Recommended remediation — review before applying.\nCisco: username admin secret <STRONG_HASH>\nFortinet: config system admin\n edit admin\n set password <STRONG_PASSWORD>\nPalo Alto: set mgt-config users admin password <STRONG_PASSWORD>",
            "CIS Benchmark - Identity Management",
            "NIST-NET-AC-001",
        ),
        build_control(
            "CIS-NET-010",
            "CIS",
            "Unrestricted Management ACL",
            "Administrative access should not be unrestricted or dangerous.",
            "Access Control",
            "CRITICAL",
            "acl_rules",
            "no_dangerous_acl",
            "heuristic",
            "Recommended remediation — review before applying.\nCisco: deny ip any any log\nFortinet: set firewall policy 1 deny\nPalo Alto: set rulebase security rules <RULE> action deny",
            "CIS Benchmark - Access Control",
            "NIST-NET-AC-001",
        ),
        build_control(
            "NIST-NET-AC-001",
            "NIST",
            "Secure Administrative Access",
            "Administrative access should be protected with secure protocols and restrictions.",
            "Access Control",
            "HIGH",
            "ssh_version",
            2,
            "equals",
            "Recommended remediation — review before applying.\nReview SSH and management access controls and disable insecure services.",
            "NIST-aligned MVP control for secure administrative access",
            "NIST-NET-AC-001",
        ),
        build_control(
            "NIST-NET-CM-001",
            "NIST",
            "Secure Baseline Configuration",
            "The baseline configuration should enforce secure settings and time synchronization.",
            "Configuration Management",
            "MEDIUM",
            "ntp_configured",
            True,
            "equals",
            "Recommended remediation — review before applying.\nReview baseline configuration settings and reapply secure management defaults.",
            "NIST-aligned MVP control for secure baseline configuration",
            "NIST-NET-CM-001",
        ),
        build_control(
            "NIST-NET-AU-001",
            "NIST",
            "Administrative Logging",
            "Administrative actions should be logged to support accountability and investigation.",
            "Audit and Accountability",
            "HIGH",
            "logging_enabled",
            True,
            "equals",
            "Recommended remediation — review before applying.\nEnable and verify device logging for administrative actions.",
            "NIST-aligned MVP control for audit and accountability",
            "NIST-NET-AU-001",
        ),
    ]


def get_controls_for_framework(framework: str) -> List[Dict[str, Any]]:
    return [control for control in get_all_controls() if control["framework"] == framework]
